### PR TITLE
Improve SVG encoding/decoding and download using a specific file name

### PR DESCRIPTION
**Pull request by clemsos**
Basically 2 things were added:
- More solid encoding (support for special characters in CSV) [Stackoverflow answer](http://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte). My exports were failing because of embed Chinese characters in SVG
- ability to name the downloaded file. I added a "download with name" function. It may be a better implementation though.

Thanks for the lib, very useful !

### CODE REVIEW

**Comment by krunkosaurus** [comment]
Thanks Clemsos, did you add additional tests to confirm your additions?

**Comment by krunkosaurus** [comment]
I'm just kidding, I'll merge this in when I get a chance to review.

**Comment by clemsos** [comment]
Hey, actually I have no idea how to test this - but Grunt does compile.  Tell me if there is any change needed

**Comment by krunkosaurus** [comment]
Hi clemsos, do you think  `download` should just accept an optional string argument to specify title and if it isn't passed it will default to 'chart'?  This would reduce needing a duplicate method.

**Comment by krunkosaurus** [comment]
Hi @clemsos. Sorry for the delay.  I have made a few updates to this library and integrated your changes by hand. I have included you on the contributors README and in the package.json contributors section.  Thank you!

**Comment by clemsos** [comment]
Cool, thanks for the lib !

**Pull request closed without merging**
